<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		
		<RumblePath>G:\SteamLibrary\steamapps\common\RUMBLE</RumblePath>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="$(RumblePath)\MelonLoader\net6\**\*.dll" Private="false" />
		<Reference Include="$(RumblePath)\MelonLoader\net35\**\*.dll" Private="false" />
		<Reference Include="$(RumblePath)\MelonLoader\Il2CppAssemblies\**\*.dll" Private="false" />
		<Reference Include="$(RumblePath)\Mods\ReplayMod.dll" Private="false" />
	</ItemGroup>
	
	<ItemGroup>
	  <None Remove="assets\AssetBundles - Shortcut.lnk" />
	  <None Remove="assets\replaystudio" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="assets\replaystudio" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="copy &quot;$(TargetPath)&quot; &quot;$(RumblePath)\Mods\$(TargetFileName)&quot;" />
	</Target>

</Project>
